using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace DevConnect.Application.Configurations;

public class SwaggerCustomDocumentFilter : IDocumentFilter
{
    public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
    {
        string introductionMarkdown = "\r\n# API Responses Structure\r\n\r\n## Successful Responses\r\n\r\nSuccessful interactions with the API return an `HTTP 200` status code. The body of the response will always feature a `\"data\"` field, housing the information relevant to the request. Depending on the specific endpoint, some responses may also include other fields at the top level, providing additional information such as pagination data.\r\n\r\n## Error Responses\r\n\r\nDifferent kinds of errors will trigger different responses, but all error responses will feature a `code` and a `message` field. The `code` represents a unique identifier for the type of error, while the `message` provides a brief explanation of the error. Occasionally, additional fields may be included in the error response.\r\n\r\nHere are some common error responses you might encounter:\r\n\r\n- `401 Unauthenticated`: This status code indicates that an API request is lacking valid authentication credentials. This will result in a `code` field value of `\"UNAUTHENTICATED\"`.\r\n\r\n- `403 Unauthorized`: This status code suggests that the API recognizes the client's request but refuses to authorize the requested data. This refusal could result from insufficient permissions provided by the client's credentials. In this instance, the `code` field will return a value of `\"UNAUTHORIZED\"`.\r\n\r\n- `422 Unprocessable Entity`: This status appears when semantic errors occur, particularly during validation processes. The `code` field for such an error will show a `\"BAD_INPUT\"` value. Additionally, the response provides an `errors` field listing all validation mistakes. Within this `errors` array, each object includes a `path`, `code`, and a `message`.\r\n\r\n- `400 Bad Request`: This status code largely represents user errors that prevent the request from being processed due to certain conditions. A common example of this includes attempts to update a resource that is not in the correct state for the update. In such situations, the response will include both a `code` and `message` field elucidating the specific error.\r\n\r\n- `404 Not Found`: This status code gets returned when a request to a specific resource results in failure because the resource is missing or doesn't exist. In these cases, the response's `code` field will show a `\"MODEL_NOT_FOUND\"` value\r\n\r\n- `500 Internal Server Error`: This status code is returned when the server encounters an internal error it can't recover from and can't provide a more specific error code. This can be due to a programming error, a database issue, or other unforeseen issues. The `code` field in the response will hold a value of `\"SERVICE_ERROR\"`.\r\n\"";

        swaggerDoc.Info.Description = introductionMarkdown;
    }
}